[build-system]
requires = ["setuptools >= 39.2.0", "wheel"]
build-backend = "setuptools.build_meta"
[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
version_files = [
  "pyproject.toml:^version",
]